### ISSUE TITLE
Sign form upload support

### ISSUE THREAD

**Issue by Maxim-Filimonov** [aws-beam/aws-elixir#75]
Hey, 
I'm using the library to implement [file upload](https://hexdocs.pm/phoenix_live_view/uploads-external.html) and trying to figure out how to do form signature. In the example, they are using hand written [generator](https://gist.github.com/chrismccord/37862f1f8b1f5148644b75d20d1cb073) for signature.

Does the library has support for something similar ?

**Comment by philss** [comment]
Hi @Maxim-Filimonov :wave: 

I don't think the lib has support for it. We do have the [signature part](https://github.com/aws-beam/aws-elixir/blob/master/lib/aws/request.ex#L491) because all the requests must be signed. But we don't have this "fields generator" based on policy. 

I think it's reasonable to move the signature part to a public API if we want to allow this type of usage. WDYT?

**Comment by Maxim-Filimonov** [comment]
Good question. Looking at SimpleS3Upload it actually does a bit more than just signature. 
It also encodes the policy. Maybe exposing a public API which would allow to create signed fields directly would be a better option. I'm not sure does AWS sdk provides something like that.

**Comment by philss** [comment]
@Maxim-Filimonov I'm closing this because we moved the signature part to a new package: https://github.com/aws-beam/aws_signature
I think there is a better place to implement something like this. Thanks!
